name: $(date:yyyyMMdd)$(rev:.rr)

trigger:
  - master

stages:
  - stage: compile
    jobs:
      - job: aspnet_build
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build PBJProject.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test PBJProject.sln --logger trx --collect:"XPlat Code Coverage"
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: cobertura
              summaryFileLocation: '**/coverage.cobertura.xml'
  - stage: analyze
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.1.100'
          - script: dotnet tool install --global dotnet-sonarscanner
          - script: |
              dotnet sonarscanner begin \
              /d:sonar.login=$SONAR_TOKEN \
              /d:sonar.host.url=https://sonarcloud.io/ \
              /d:sonar.cs.opencover.reportsPaths=**/TestResults/*/coverage.opencover.xml \
              /d:sonar.javascript.exclusions=**/PBJProject.Client/wwwroot/** \
              /d:sonar.cs.vstest.reportsPaths=**/*.trx \
              /k:benjaminclegg \
              /o:benjaminclegg
              dotnet build PBJProject.sln
              dotnet test PBJProject.sln --logger trx /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
              dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
            env:
              SONAR_TOKEN: $(sonar.token)
  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: docker image build -t benjaminclegg/devops:$BUILD_NAME .
            env:
              BUILD_NAME: $(Build.DefinitionName)
          - script: docker login --username $DOCKER_USER --password $DOCKER_TOKEN
            env:
              DOCKER_TOKEN: $(docker.token)
              DOCKER_USER: $(docker.user)
          - script: docker image push benjaminclegg/devops:$BUILD_NAME
            env:
              BUILD_NAME: $(Build.DefinitionName)
